"api_base": {
  "GPT": "https://openrouter.ai/api/v1",
  #  "GPT": "https://api.deepseek.com",
  "VLM": "https://api.deepseek.com",
}
"api_key": {
  "GPT": "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",
  "VLM": "sk-cBSqdkbEj5pPeY9pg2TBxgWMX7E8lmLTh4JzamXoR7L1Oymp"
}
"model": {
  "VLM": "",
  #  "GPT": "gpt-4o-2024-11-20",
  # "GPT": "DMXAPI-HuoShan-DeepSeek-V3",
  # "GPT": "deepseek/deepseek-chat-v3-0324:free",
  "GPT": "tngtech/deepseek-r1t2-chimera:free",
#  "GPT": "o1-mini",
  # "QWEN": "qwen-vl-plus",
  # "CLAUDE": "input the claude model here"
}